apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "meshcap.fullname" . }}
  labels:
    {{- include "meshcap.labels" . | nindent 4 }}
data:
  GOR_S3_BUCKET: {{ .Values.collector.s3Bucket | quote }}
  GOR_S3_PREFIX: {{ .Values.collector.s3Prefix | quote }}
  GOR_S3_REGION: {{ .Values.collector.s3Region | quote }}
  GOR_S3_ENDPOINT: {{ .Values.collector.s3Endpoint | quote }}
  GOR_FLUSH_INTERVAL: {{ .Values.collector.flushInterval | quote }}
  GOR_BUFFER_CHAN_SIZE: {{ .Values.collector.bufferChanSize | int64 | quote }}
  GOR_MAX_BODY_SIZE: {{ .Values.collector.maxBodySize | int64 | quote }}
  GOR_COLLECTOR_PORT: {{ .Values.collector.port | int64 | quote }}
  GOR_METRICS_PORT: {{ .Values.collector.metricsPort | int64 | quote }}
  GOR_LOG_LEVEL: {{ .Values.collector.logLevel | quote }}
